### PR TITLE
Fix how cached paired planes search for movies.

### PR DESCRIPTION
**Pull request by arielleleon**
aind-ophys-motion-correction copied the raw h5 file to it's results directory for decrosstalk processing. The pipeline contains a new channel connection from the raw data to decrosstalk so that the file never needs to be copied in the first place. Also added a debug mode.

### CODE REVIEW

**Review by mattjdavis — APPROVED** [review]
looks like a helpful debug mode was added, i see no problems

**Comment by mattjdavis** [comment]
given that 
"oeid" (ophys_experiment_id) is no longer used in CO era, one could relace variables names with "plane_name". just a note we could change in the future

**Comment by arielleleon** [comment]
@mattjdavis, I put that into an issue: https://github.com/AllenNeuralDynamics/aind-ophys-decrosstalk-roi-images/issues/24

**Review by jkim0731 — APPROVED** [review]
Looks good to me.
Input parameters in some of the functions need to be documented. (e.g., def paired_plane_cached_movie: chunk_size, non_rigid, block_size, return_rframes, etc.)

**Pull request merged**
